name = "oj-proxy-worker"
main = "src/index.ts"
compatibility_date = "2025-10-28"

[[d1_databases]]
binding = "DB" # 在代码中通过 env.DB 访问
database_name = "proxy-db"
database_id = "21c5ba97-b53b-43ce-bbc0-595666a92f5c" # 替换为你的 D1 数据库 ID

[vars]
OJ_ORIGIN = "https://local.cwoi.com.cn:8443" 

[[build.rules]]
type = "Text"
globs = ["**/*.html"]